### ISSUE TITLE
Feature. Support variable-length breathing gestures

### ISSUE THREAD

**Issue by aarontabor** [hcilab/BreathingSonarJS#3]
# Overview
For simplicity, the current system only supports recording and recognizing breathing gestures that are the same length as the sonar's internal `rollingWindow`. This is probably okay for the time being, but it will certainly lead to limitations as we use this tool in more generalized settings.

# Tasks
- [ ] Think about how best to record and store variable-length breathing patterns
  - [ ] I believe the current .csv format will work
- [ ] What happens if a recorded gesture is longer than the rolling window?
  - [ ] Should I maintain a separate signal history for this purpose?
- [ ] Should I be concerned with time-warping (e.g., so we could detect slow and fast inhales with the same training pattern)?

**Comment by aarontabor** [comment]
For now, I've completely removed gesture recognition capabilities from the library... think about whether or not we want to support breathing gestures in general before approaching this issue.
